version: 2.1
orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.4.0
executors:
  image: cimg/base:stable
jobs:
  checkout:
    steps:
      - git-shallow-clone/checkout_shallow

workflows:
  build:
    jobs:
      - checkout:
          filters:
            tags:
              only: /.*/
