version: 2.1
orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.4.0
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout_shallow
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout_shallow
      - run: echo "this is the test job"

workflows:
  build_and_test:
    jobs:
      - build
      - test
