version: 2.1
orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@dev:alpha
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout
      - run: git submodule update --init --recursive
      - run: echo "this is the build job"
      - run: git submodule status --recursive
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout_advanced
      - run: echo "this is the test job"

workflows:
  build_and_test:
    jobs:
      - build
      - test
