version: 2.1
orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@dev:alpha
jobs:
  checkout:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout
      - run: git submodule update --init --recursive
      - run: echo "this is the build job"
      - run: git submodule status --recursive

  checkout_advanced:
    docker:
      - image: cimg/base:stable
    steps:
      - git-shallow-clone/checkout_advanced
      - run: git submodule update --init --recursive
      - run: echo "this is the test job"
      - run: git submodule status --recursive

workflows:
  build_and_test:
    jobs:
      - checkout
      - checkout_advanced
